from quantum_core.benchmarking import (
    append_inversion_gate,
    fit_rb_decay,
    generate_random_clifford_sequence,
    run_randomized_benchmarking_trial,
)
from quantum_core.circuit import bind_parameters
from quantum_core.cli import run_audit_cli
from quantum_core.decoding import (
    build_matching_graph,
    decode_mwpm,
    minimum_weight_perfect_matching,
)
from quantum_core.density_matrix import (
    amplitude_damping_kraus,
    apply_kraus_channel,
    apply_unitary_density_matrix,
    bit_flip_kraus,
    density_matrix_from_statevector,
    density_matrix_purity,
    density_matrix_zero,
    depolarizing_kraus,
    phase_flip_kraus,
)
from quantum_core.evidence import (
    MetricEvidence,
    compute_sha256_hash,
    generate_reproducible_evidence,
)
from quantum_core.error_models import (
    evaluate_palindromic_coherent_suppression,
    inject_coherent_rotation_noise,
    inject_stochastic_pauli_noise,
    state_fidelity,
)
from quantum_core.optimization import (
    circuit_depth,
    gate_count,
    optimize_circuit,
    two_qubit_gate_count,
)
from quantum_core.gates import (
    HADAMARD,
    IDENTITY_2,
    PAULI_X,
    PAULI_Y,
    PAULI_Z,
    PHASE_S,
    PHASE_T,
    compose_gates,
    global_phase_equivalent,
    h_matrix,
    i_matrix,
    is_hermitian,
    is_unitary,
    rotation_matrix,
    rx_matrix,
    ry_matrix,
    rz_matrix,
    s_matrix,
    t_matrix,
    x_matrix,
    y_matrix,
    z_matrix,
)
from quantum_core.magic_states import (
    bravyi_haah_14_to_2_distillation,
    bravyi_haah_syndrome_extraction_circuit,
    distill_magic_t_state_toy,
    inject_t_gate_via_teleportation,
    prepare_magic_t_state,
)
from quantum_core.mps import (
    MPSState,
    apply_single_qubit_gate_mps,
    apply_two_qubit_gate_mps,
    mps_norm,
    mps_to_statevector,
    mps_zero_state,
)
from quantum_core.openqasm import from_openqasm3, to_openqasm3
from quantum_core.qldpc import (
    QLDPCCodeSpec,
    bivariate_bicycle_code_spec,
    compare_surface_vs_qldpc_footprint,
)
from quantum_core.routing import grid_manhattan_distance, route_circuit_2d
from quantum_core.synthesis import decompose_rz_to_clifford_t, synthesize_circuit_clifford_t
from quantum_core.zcc_codegen import generate_zcc_c_code
from quantum_core.measurement import (
    marginal_probabilities,
    measure_qubit,
    probabilities,
    sample_counts,
)
from quantum_core.registry import (
    REGISTRY_PATH,
    import_module_from_path,
    load_json_object,
    require_finite_metric,
    require_mapping,
    resolve_project_path,
    verify_registry_artifacts,
)
from quantum_core.simulator import (
    apply_controlled_x,
    apply_controlled_z,
    apply_operation,
    apply_single_qubit_gate,
    apply_swap,
    apply_toffoli,
    ccx_matrix,
    cnot_matrix,
    cz_matrix,
    embed_single_qubit_gate,
    execute_gate_sequence,
    swap_matrix,
    zero_state,
)
from quantum_core.stabilizers import (
    PauliOperator,
    StabilizerCode,
    extract_syndrome,
    steane_code_7_1_3,
    surface_code_distance_3,
    surface_code_distance_5,
)
from quantum_core.triorthogonal import (
    bravyi_haah_14_2_matrix,
    bravyi_kitaev_15_1_matrix,
    is_triorthogonal,
)
from quantum_core.types import (
    CircuitValidationError,
    GateAxis,
    GateOperation,
    RegistryValidationError,
    StateVector,
)
from quantum_core.validation import normalize_gate, normalize_gates

__version__ = "1.0.0"

__all__ = [
    "HADAMARD",
    "IDENTITY_2",
    "PAULI_X",
    "PAULI_Y",
    "PAULI_Z",
    "PHASE_S",
    "PHASE_T",
    "CircuitValidationError",
    "GateAxis",
    "GateOperation",
    "MetricEvidence",
    "MPSState",
    "PauliOperator",
    "QLDPCCodeSpec",
    "RegistryValidationError",
    "StabilizerCode",
    "StateVector",
    "amplitude_damping_kraus",
    "apply_controlled_x",
    "apply_controlled_z",
    "apply_kraus_channel",
    "apply_operation",
    "apply_single_qubit_gate",
    "apply_single_qubit_gate_mps",
    "apply_swap",
    "apply_toffoli",
    "apply_two_qubit_gate_mps",
    "apply_unitary_density_matrix",
    "append_inversion_gate",
    "bind_parameters",
    "bit_flip_kraus",
    "bivariate_bicycle_code_spec",
    "bravyi_haah_14_2_matrix",
    "bravyi_haah_14_to_2_distillation",
    "bravyi_haah_syndrome_extraction_circuit",
    "bravyi_kitaev_15_1_matrix",
    "build_matching_graph",
    "ccx_matrix",
    "circuit_depth",
    "cnot_matrix",
    "compare_surface_vs_qldpc_footprint",
    "compose_gates",
    "compute_sha256_hash",
    "cz_matrix",
    "decode_mwpm",
    "decompose_rz_to_clifford_t",
    "density_matrix_from_statevector",
    "density_matrix_purity",
    "density_matrix_zero",
    "depolarizing_kraus",
    "distill_magic_t_state_toy",
    "embed_operator",
    "evaluate_palindromic_coherent_suppression",
    "execute_circuit",
    "execute_gate_sequence",
    "fit_rb_decay",
    "from_openqasm3",
    "gate_count",
    "generate_random_clifford_sequence",
    "generate_reproducible_evidence",
    "generate_zcc_c_code",
    "get_single_qubit_gate",
    "grid_manhattan_distance",
    "hadamard_matrix",
    "global_phase_equivalent",
    "h_matrix",
    "i_matrix",
    "import_module_from_path",
    "inject_coherent_rotation_noise",
    "inject_stochastic_pauli_noise",
    "inject_t_gate_via_teleportation",
    "is_hermitian",
    "is_triorthogonal",
    "is_unitary",
    "load_json_object",
    "marginal_probabilities",
    "measure_qubit",
    "MetricEvidence",
    "minimum_weight_perfect_matching",
    "mps_norm",
    "mps_to_statevector",
    "mps_zero_state",
    "normalize_gate",
    "normalize_gates",
    "optimize_circuit",
    "phase_flip_kraus",
    "prepare_magic_t_state",
    "probabilities",
    "require_finite_metric",
    "require_mapping",
    "resolve_project_path",
    "route_circuit_2d",
    "run_audit_cli",
    "run_randomized_benchmarking_trial",
    "rx_matrix",
    "ry_matrix",
    "rz_matrix",
    "s_matrix",
    "sample_counts",
    "steane_code_7_1_3",
    "surface_code_distance_3",
    "surface_code_distance_5",
    "swap_matrix",
    "synthesize_circuit_clifford_t",
    "t_matrix",
    "to_openqasm3",
    "two_qubit_gate_count",
    "verify_registry_artifacts",
    "x_matrix",
    "y_matrix",
    "z_matrix",
    "zero_state",
]
